### ISSUE TITLE
socket-recv! not working - "make-sized-byte-string: unsupported"

### ISSUE THREAD

**Issue by Cazra** [jeapostrophe/zeromq#16]
I'm having trouble using the `socket-recv!` function. Whenever I try to invoke it, I get the following error:
`make-sized-byte-string: unsupported`

Here's a minimal code example for how I'm trying to use it: 
```
(define (run-zmq-server port)
  (call-with-context (λ (ctx)
    (call-with-socket ctx 'PULL (λ (socket)
      (socket-bind! socket (format "tcp://127.0.0.1:~a" port))
      (display (format "Started mock CE Service on port ~a.\n" port))

      (let loop ()
        (let* ([dto-bytes (socket-recv! socket)] ; <--- The error is getting thrown here.
               [req (_bytes->dto dto-bytes)]
               [msg-type (hash-ref req 'messageType #f)])
          (cond
            [(equal? msg-type 'CLOSE)
              (display "Closing mock CE Service.\n")]
            [else
              (display (format "Received message:\n~a\n\n" msg-type))
              (loop)]))))))))
```

**Comment by jeapostrophe** [comment]
That function is not supported in ChezScheme --- https://docs.racket-lang.org/foreign/foreign_pointer-funcs.html#%28def._%28%28quote._~23~25foreign%29._make-sized-byte-string%29%29

**Comment by Cazra** [comment]
Are there any plans to add compatibility to this project to support `socket-recv!` in ChezScheme?

**Comment by mflatt** [comment]
It looks like the use here

```
 (make-sized-byte-string (msg-data-pointer m) (msg-size m))
```

could be replaced with

```
(let ([s (make-bytes (msg-size m))])
  (memcpy s (msg-data-pointer m) (msg-size m))
  s)
```

This copies data out of the message instead of pointing inside message. But `socket-recv!` was copying anyway, and the` bytes-copy` there could be removed.
